Repository necst-telescope/necst-msgs, pull requests merged in 2022-10, with the labels that each got.

#29 Auto-generate documentation
  .github/workflows/gh-pages.yml
  .gitignore
  docs/generate_docs.py
Labels: documentation, enhancement

#30 Change title font in documentation
  docs/generate_docs.py
Labels: documentation

#32 Support Sphinx-like section in docs
  .github/workflows/gh-pages.yml
  docs/generate_docs.py
  msg/AlertMsg.msg
  msg/CoordMsg.msg
  msg/PIDMsg.msg
  msg/TimedAzElFloat64.msg
  msg/TimedAzElInt64.msg
  srv/AuthoritySrv.srv
Labels: documentation, enhancement

#34 Add data type for file transfer service
  CMakeLists.txt
  srv/File.srv
Labels: enhancement

#36 Change data type for threshold field of `AlertMsg`
  msg/AlertMsg.msg
  srv/File.srv
Labels: enhancement

#38 #37 add TimeFloat64.msg
  CMakeLists.txt
  msg/TimedFloat64.msg
Labels: enhancement
